version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "elimarcavalli"
    assignees:
      - "elimarcavalli"
    groups:
      pydantic:
        patterns:
          - "pydantic"
          - "pydantic_core"
          - "pydantic-core"
          - "pydantic-settings"