# Perfil de configuração para Agente Autônomo Enterprise-Grade
# Otimizado para trabalho incessante e autonomia máxima

system:
  debug_mode: false
  log_level: INFO
  log_requests: true
  log_responses: true
  session_timeout: 28800  # 8 horas para sessões longas
  auto_save_sessions: true

  # Configurações específicas para agente autônomo
  autonomous_mode: true
  max_task_queue_size: 100
  task_execution_timeout: 3600  # 1 hora por tarefa
  auto_retry_failed_tasks: true
  max_retries: 3

  # Monitoramento avançado
  enable_metrics: true
  metrics_interval: 300  # 5 minutos
  enable_telemetry: true

  # Auto-improvement
  enable_self_analysis: true
  auto_optimize_performance: true
  learn_from_failures: true

agent:
  max_context_tokens: 32000  # Contexto expandido para tarefas complexas
  context_optimization: true
  auto_discover_tools: true
  auto_discover_parsers: true
  rag_enabled: true

  # Capacidades autônomas
  autonomous_task_execution: true
  auto_break_down_complex_tasks: true
  auto_validate_outputs: true
  auto_suggest_improvements: true

  # Planejamento e execução
  enable_task_planning: true
  enable_parallel_execution: true
  max_parallel_tasks: 5

  # Aprendizado contínuo
  enable_continuous_learning: true
  save_successful_patterns: true
  adapt_to_user_preferences: true

ui:
  theme: autonomous
  show_timestamps: true
  auto_complete: true
  emoji_support: false  # Mais profissional
  rich_formatting: true

  # Interface otimizada para autonomia
  show_task_progress: true
  show_performance_metrics: true
  auto_expand_detailed_logs: false
  minimal_confirmations: true  # Menos interrupções

# Configurações específicas para personas autônomas
personas:
  default_persona: "autonomous_developer"
  auto_switch_personas: true  # Muda persona baseado na tarefa
  persona_switch_confidence_threshold: 0.8

  # Configurações de comunicação para agente autônomo
  communication:
    be_proactive: true
    report_progress_regularly: true
    ask_clarifying_questions_when_needed: true
    provide_detailed_explanations: true
    suggest_optimizations: true

# Configurações de performance
performance:
  cache_enabled: true
  cache_size_mb: 512
  parallel_processing: true
  optimize_memory_usage: true

  # Auto-scaling baseado na carga
  auto_scale_resources: true
  min_worker_threads: 2
  max_worker_threads: 8

# Configurações de segurança para operação autônoma
security:
  sandbox_code_execution: true
  validate_file_operations: true
  restrict_network_access: false  # Permite buscar informações online
  log_all_operations: true

  # Limites de segurança
  max_file_size_mb: 100
  max_files_per_operation: 50
  allowed_file_extensions: [".py", ".js", ".ts", ".yaml", ".yml", ".json", ".md", ".txt", ".sql", ".html", ".css"]

# Configurações de monitoramento
monitoring:
  enable_health_checks: true
  health_check_interval: 60  # 1 minuto

  # Métricas de performance
  track_response_times: true
  track_success_rates: true
  track_resource_usage: true

  # Alertas automáticos
  enable_alerts: true
  alert_on_high_failure_rate: true
  alert_on_performance_degradation: true

# Integração com ferramentas externas
integrations:
  enable_git_integration: true
  enable_package_management: true
  enable_testing_frameworks: true
  enable_linting_tools: true

  # APIs e serviços
  enable_web_search: true
  enable_documentation_lookup: true
  enable_code_analysis_tools: true