# Perfil Enterprise com máxima segurança e compliance

system:
  debug_mode: false
  log_level: INFO
  log_requests: true
  log_responses: true
  session_timeout: 7200  # 2 horas
  auto_save_sessions: true

  # Auditoria e compliance
  enable_audit_logging: true
  audit_log_retention_days: 365
  require_user_confirmation: true  # Para operações críticas
  enable_change_tracking: true

agent:
  max_context_tokens: 16000
  context_optimization: true
  auto_discover_tools: false  # Controle manual em ambiente enterprise
  auto_discover_parsers: false
  rag_enabled: true

  # Validações rigorosas
  validate_all_operations: true
  require_approval_for_file_changes: true
  backup_before_modifications: true

ui:
  theme: enterprise
  show_timestamps: true
  auto_complete: true
  emoji_support: false
  rich_formatting: true

security:
  sandbox_code_execution: true
  validate_file_operations: true
  restrict_network_access: true  # Máxima segurança
  log_all_operations: true
  encrypt_logs: true

  # Políticas rigorosas
  max_file_size_mb: 50
  max_files_per_operation: 20
  allowed_file_extensions: [".py", ".js", ".yaml", ".json", ".md", ".txt"]

monitoring:
  enable_health_checks: true
  health_check_interval: 30
  enable_performance_monitoring: true
  enable_security_monitoring: true

  # Compliance e auditoria
  track_all_user_actions: true
  generate_compliance_reports: true
  alert_on_security_violations: true