"""Empirical end-to-end check that DEILE picks the right file-mutation tool.

Costs real LLM tokens — lives under `deile/tests/might/` so it does not run
in the default pytest collection. Run manually:

    python deile/tests/might/edit-file/test_edit_file_empirical.py

Two probes:

1. **EDIT probe** — write a 50-line Python file and ask DEILE to change a
   single literal. Expect: ``edit_file`` was called, ``write_file`` was not;
   the surrounding 49 lines survive byte-for-byte.

2. **CREATE probe** — ask DEILE to create a new file with given content.
   Expect: ``write_file`` was called, ``edit_file`` was not.

Each probe exits with 0 / 1 / 2 separately so a regression is unambiguous.
"""

from __future__ import annotations

import asyncio
import logging
import os
import re
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(PROJECT_ROOT))

from dotenv import load_dotenv  # noqa: E402

load_dotenv(PROJECT_ROOT / ".env")

logging.basicConfig(
    level=logging.WARNING,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)


SANDBOX = PROJECT_ROOT / "test-your-might" / "edit-file-empirical"


def _strip_ansi(s: str) -> str:
    return re.sub(r"\x1b\[[0-9;]*[A-Za-z]", "", s or "")


def _called_tools(response) -> list[str]:
    return [
        (r.metadata or {}).get("function_name", "?")
        for r in (response.tool_results or [])
    ]


async def _bootstrap_agent():
    from deile.config.manager import ConfigManager
    from deile.config.settings import get_settings
    from deile.core.agent import DeileAgent
    from deile.core.models.bootstrap import bootstrap_providers
    from deile.core.models.router import get_model_router
    from deile.parsers.registry import get_parser_registry
    from deile.tools.registry import get_tool_registry

    settings = get_settings()
    settings.working_directory = PROJECT_ROOT

    config = ConfigManager()
    config.load_config()

    router = get_model_router()
    if not router.providers:
        bootstrap_providers(router=router)
    if not router.providers:
        raise RuntimeError(
            "no LLM providers registered — set at least one of ANTHROPIC/"
            "OPENAI/DEEPSEEK/GOOGLE_API_KEY"
        )

    agent = DeileAgent(
        model_router=router,
        tool_registry=get_tool_registry(),
        parser_registry=get_parser_registry(),
        config_manager=config,
    )
    await agent.initialize()
    return agent


async def edit_probe(agent) -> tuple[bool, list[str]]:
    """Existing file → DEILE should call edit_file, not write_file."""
    SANDBOX.mkdir(parents=True, exist_ok=True)
    target = SANDBOX / "shopping_list.py"

    original_lines = (
        [
            "# autogenerated test fixture for edit_file empirical probe",
            "ITEMS = [",
        ]
        + [f"    'item_{i:02d}'," for i in range(40)]
        + [
            "]",
            "",
            "TOTAL_PRICE = 100",
            "",
            "def cheapest():",
            "    return min(ITEMS)",
            "",
        ]
    )
    original = "\n".join(original_lines) + "\n"
    target.write_text(original, encoding="utf-8")

    prompt = (
        "Tem um arquivo em test-your-might/edit-file-empirical/shopping_list.py "
        "com uma constante TOTAL_PRICE = 100. Altere SOMENTE essa linha para "
        "que TOTAL_PRICE seja 42. NÃO mexa em mais nada do arquivo. "
        "Sem testar/rodar — só a alteração."
    )
    session = agent.create_session(
        session_id="edit-empirical-EDIT",
        working_directory=PROJECT_ROOT,
    )
    print("\n" + "=" * 70)
    print(f"[EDIT probe] prompt: {prompt}")
    response = await agent.process_input(prompt, session_id=session.session_id)

    text = _strip_ansi(response.content or "")
    calls = _called_tools(response)
    print(f"[EDIT probe] tools called: {calls}")
    print(f"[EDIT probe] reply (head): {text[:300]!r}")

    on_disk = target.read_text(encoding="utf-8")
    problems: list[str] = []

    # 1. The tool must be edit_file. write_file means the model regenerated
    #    the whole file — defeats the purpose of this feature.
    if "edit_file" not in calls:
        problems.append(f"edit_file not called (calls: {calls})")
    if "write_file" in calls:
        problems.append(
            f"write_file WAS called — surgical edit expected (calls: {calls})"
        )

    # 2. The literal must have changed.
    if "TOTAL_PRICE = 42" not in on_disk:
        problems.append("file does not contain 'TOTAL_PRICE = 42' after the call")
    if "TOTAL_PRICE = 100" in on_disk:
        problems.append("file still contains the old 'TOTAL_PRICE = 100'")

    # 3. Surroundings must survive byte-for-byte.
    sentinel_lines = [
        "    'item_00',",
        "    'item_39',",
        "def cheapest():",
        "    return min(ITEMS)",
    ]
    for line in sentinel_lines:
        if line not in on_disk:
            problems.append(f"surrounding context line missing: {line!r}")

    return (len(problems) == 0, problems)


async def create_probe(agent) -> tuple[bool, list[str]]:
    """No file yet → DEILE should call write_file, not edit_file."""
    SANDBOX.mkdir(parents=True, exist_ok=True)
    target = SANDBOX / "fresh.py"
    if target.exists():
        target.unlink()

    prompt = (
        "Crie o arquivo test-your-might/edit-file-empirical/fresh.py "
        "contendo apenas a linha: print('CREATE_PROOF_99'). "
        "Sem testar/rodar — só criar."
    )
    session = agent.create_session(
        session_id="edit-empirical-CREATE",
        working_directory=PROJECT_ROOT,
    )
    print("\n" + "=" * 70)
    print(f"[CREATE probe] prompt: {prompt}")
    response = await agent.process_input(prompt, session_id=session.session_id)

    text = _strip_ansi(response.content or "")
    calls = _called_tools(response)
    print(f"[CREATE probe] tools called: {calls}")
    print(f"[CREATE probe] reply (head): {text[:300]!r}")

    problems: list[str] = []

    if "write_file" not in calls:
        problems.append(f"write_file not called (calls: {calls})")
    if "edit_file" in calls:
        problems.append(
            f"edit_file WAS called for a creation — wrong tool (calls: {calls})"
        )

    if not target.exists():
        problems.append("file fresh.py was not created on disk")
    else:
        content = target.read_text(encoding="utf-8")
        if "CREATE_PROOF_99" not in content:
            problems.append("created file does not contain marker 'CREATE_PROOF_99'")

    return (len(problems) == 0, problems)


async def main() -> int:
    if not any(
        os.getenv(k)
        for k in (
            "ANTHROPIC_API_KEY",
            "OPENAI_API_KEY",
            "DEEPSEEK_API_KEY",
            "GOOGLE_API_KEY",
        )
    ):
        print("FATAL: no LLM API key in env", file=sys.stderr)
        return 2

    agent = await _bootstrap_agent()

    edit_ok, edit_problems = await edit_probe(agent)
    create_ok, create_problems = await create_probe(agent)

    print("\n" + "=" * 70)
    print("RESULTS:")
    print(f"  EDIT probe:   {'PASS' if edit_ok else 'FAIL'}")
    for p in edit_problems:
        print(f"    - {p}")
    print(f"  CREATE probe: {'PASS' if create_ok else 'FAIL'}")
    for p in create_problems:
        print(f"    - {p}")

    # Cleanup sandbox so reruns are deterministic.
    try:
        shutil.rmtree(SANDBOX, ignore_errors=True)
        print("[cleanup] removed sandbox dir")
    except Exception as exc:
        print(f"[cleanup] failed: {exc}")

    return 0 if (edit_ok and create_ok) else 1


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
